[package]
name = "geoloc"
version = "0.1.0"
edition = "2021"
authors = ["styvane <4968379+styvane@users.noreply.github.com>"]
repository = "https://github.com/styvane/geoloc"
rust-version = "1.65"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0"
csv = "1.1"
rustyline = "10.0.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
tempfile = "3"